### PR TITLE
Fix GCS Token Refresh

### LINKED ISSUE #1109: GCS does not refresh OAuth2 tokens
**Problem**

The GCS Sink uses `auth::json_api_client` which in turn called `authenticate_bearer` which in turn fetches a OAuth2 token. This happens during startup time meaning the token is not re-generated or refreshed. Part of the OAuth flow is that tokens have a limited lifetime and require periodic refresh.

I am not sure what the times for google oauth tokens are but they probably range from hours to days so this is nothing we would have seen in tests, that said in production the current GCS sink will eventually fail to authenticate and throw errors, this will be very confusing to users.

**Possible Solution(s)**

Fortunately `Token` from `gouth` handles this logic for us. If it is cached and `header_value` is called on reach request it will take the token lifetime into account and request a new bearer token whenever the current one is outdated.

### PR DESCRIPTION
**Pull request by dak-x**
Signed-off-by: Daksh Chauhan <dak-x@outlook.com>

# Pull request

## Description
Introduce a wrapper around the `reqwest::Client`.

## Related

* Related Issues: fixes #1109

## Checklist

* [X] The RFC, if required, has been submitted and approved
* [X] Any user-facing impact of the changes is reflected in docs.tremor.rs
* [X] The code is tested
* [X] Use of unsafe code is reasoned about in a comment
* [X] Update CHANGELOG.md appropriately, recording any changes, bug fixes, or other observable changes in behavior
* [X] The performance impact of the change is measured (see below)

### CODE REVIEW

**Review by Licenser — DISMISSED** [review]
I really like this aproach! Nicely done :) thank you! 🚀

**Comment by darach** [comment]
Nice work! 🎸

**Review by mfelsche — APPROVED** [review]

File: src/connectors/gcp/auth.rs [hunk 1]
```diff
@@ -21,28 +21,59 @@ use gouth::Token;
 use reqwest::header::HeaderMap;
 use reqwest::Client;
 
-/// returns `gouth::Token` object and bearer token header as a string
-pub(crate) fn authenticate_bearer() -> Result<(Token, String)> {
-    let token = Token::new()?;
-    let header_value_string = token.header_value()?.to_string();
-    Ok((token, header_value_string))
+pub(crate) struct GcsClient {
```
Comment (mfelsche) [inline src/connectors/gcp/auth.rs:24]: Since this has no coverage and can only get coverage when tested against GCS in some way, i would be ok with adding `#[cfg(not(tarpaulin_include))]`, so the coverage doesnt drop overall.

Comment (mfelsche) [reply src/connectors/gcp/auth.rs:25]: I think we also need to put this on the `impl` part. :/

**Review by Licenser — APPROVED** [review]

**Comment by Licenser** [comment]
Thank you @dak-x!
